version: "3"

services:
  postgres:
    image: library/postgres:12.2-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - postgres_newsfeed_data:/var/lib/postgresql/data

  redis:
    image: library/redis:6-alpine

  web:
    build: .
    ports:
      - 3000:8080
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  postgres_newsfeed_data: