const FETCH_ARTICLES = "FETCH_ARTICLES"
const SELECT_CATEGORY = "SELECT_CATEGORY"
const SET_CURRENT_USER = "SET_CURRENT_USER"
const SHOW_TOAST = "SHOW_TOAST"
const HIDE_TOAST = "HIDE_TOAST"
const REFRESH_TOKEN = "REFRESH_TOKEN"
const SET_SESSION = "SET_SESSION"
const SIGN_OUT = "SIGN_OUT"
const FETCH_BOOKMARKS = "FETCH_BOOKMARKS"
const LOADING = "loading"
const AUTHENTICATED = "authenticated"
const DENIED = "denied"
const BOOKMARK = "bookmark"
const ARTICLE = "article"
const EMPTY_ARTICLES = "EMPTY_ARTICLES"
const MOBILE_DRAWER_WIDTH = 60
const DESKTOP_DRAWER_WIDTH = 180
const SET_DRAWER_WIDTH = 'SET_DRAWER_WIDTH'
const REMOVE_RESOURCE = 'REMOVE_RESOURCE'
const CHECK_SESSION = 'CHECK_SESSION'


export {
    FETCH_ARTICLES, SELECT_CATEGORY,
    SET_CURRENT_USER, SHOW_TOAST, HIDE_TOAST, REFRESH_TOKEN,
    SET_SESSION, FETCH_BOOKMARKS, AUTHENTICATED, DENIED, LOADING,
    BOOKMARK, ARTICLE, EMPTY_ARTICLES, MOBILE_DRAWER_WIDTH, DESKTOP_DRAWER_WIDTH,
    SET_DRAWER_WIDTH, REMOVE_RESOURCE, SIGN_OUT, CHECK_SESSION
}